# Generated by Django 5.2.2 on 2025-06-18 16:35

import django.db.models.deletion
import encrypted_fields.fields
import ox.apps.content.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("caps", "0001_initial"),
        ("ox_contacts", "0002_alter_person_organisations"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="Id")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("smtp_host", models.CharField(max_length=255, verbose_name="SMTP: Host")),
                ("smtp_port", models.PositiveIntegerField(default=587, verbose_name="SMTP: Port")),
                (
                    "smtp_username",
                    encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name="SMTP: Username"),
                ),
                (
                    "smtp_password",
                    encrypted_fields.fields.EncryptedCharField(max_length=128, verbose_name="SMTP: Password"),
                ),
                (
                    "smtp_encryption",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "NONE"), (1, "TLS"), (2, "SSL")], verbose_name="SMTP: Encryption"
                    ),
                ),
                ("imap_host", models.CharField(blank=True, max_length=255, null=True, verbose_name="IMAP: Host")),
                ("imap_port", models.PositiveIntegerField(blank=True, null=True, verbose_name="IMAP: Port")),
                (
                    "imap_username",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=255, null=True, verbose_name="IMAP: Username"
                    ),
                ),
                (
                    "imap_password",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=128, null=True, verbose_name="IMAP: Password"
                    ),
                ),
                ("imap_ssl", models.BooleanField(default=True, verbose_name="IMAP: Use SSL")),
                ("imap_folder", models.CharField(default="INBOX", max_length=255, verbose_name="IMAP: Folder")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="caps.agent", verbose_name="Owner"
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Account",
                "verbose_name_plural": "Email Accounts",
            },
        ),
        migrations.CreateModel(
            name="MailAccountAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name="Id")),
                (
                    "expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Defines an expiration date after which the access is not longer valid.",
                        null=True,
                        verbose_name="Expiration",
                    ),
                ),
                ("grants", models.JSONField(blank=True, verbose_name="Granted permissions")),
                (
                    "emitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Emitter",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived",
                        to="ox_mails.mailaccountaccess",
                        verbose_name="Origin",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="ox_mails.mailaccount",
                        verbose_name="Target",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "proxy": False,
            },
        ),
        migrations.CreateModel(
            name="MailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="Id")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("subject", models.CharField(max_length=128, verbose_name="Subject")),
                ("content", ox.apps.content.models.RichTextField(verbose_name="Content")),
                (
                    "account",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ox_mails.mailaccount"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="caps.agent", verbose_name="Owner"
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
            },
        ),
        migrations.CreateModel(
            name="MailTemplateAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name="Id")),
                (
                    "expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Defines an expiration date after which the access is not longer valid.",
                        null=True,
                        verbose_name="Expiration",
                    ),
                ),
                ("grants", models.JSONField(blank=True, verbose_name="Granted permissions")),
                (
                    "emitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Emitter",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived",
                        to="ox_mails.mailtemplateaccess",
                        verbose_name="Origin",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="ox_mails.mailtemplate",
                        verbose_name="Target",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "proxy": False,
            },
        ),
        migrations.CreateModel(
            name="OutMail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="Id")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Draft"), (1, "Sending"), (2, "Sent")], default=0, verbose_name="Status"
                    ),
                ),
                ("context", models.JSONField(default=dict, verbose_name="Context")),
                (
                    "subject",
                    models.TextField(
                        default="", help_text="When provided, overrides template's content", verbose_name="Subject"
                    ),
                ),
                (
                    "content",
                    ox.apps.content.models.RichTextField(
                        default="", help_text="When provided, overrides template's content.", verbose_name="Message"
                    ),
                ),
                ("contacts", models.ManyToManyField(to="ox_contacts.person")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="caps.agent", verbose_name="Owner"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ox_mails.mailtemplate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mail",
                "verbose_name_plural": "Mails",
            },
        ),
        migrations.CreateModel(
            name="OutMailAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name="Id")),
                (
                    "expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Defines an expiration date after which the access is not longer valid.",
                        null=True,
                        verbose_name="Expiration",
                    ),
                ),
                ("grants", models.JSONField(blank=True, verbose_name="Granted permissions")),
                (
                    "emitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Emitter",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived",
                        to="ox_mails.outmailaccess",
                        verbose_name="Origin",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="ox_mails.outmail",
                        verbose_name="Target",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "proxy": False,
            },
        ),
    ]
