# Generated by Django 5.2.2 on 2025-11-08 14:59

import django.db.models.deletion
import encrypted_fields.fields
import ox.apps.content.models
import ox.apps.mails.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("caps", "0001_initial"),
        ("ox_files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="Id")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Draft"), (1, "Sending"), (2, "Sent"), (3, "Error")],
                        default=0,
                        verbose_name="State",
                    ),
                ),
                ("context", models.JSONField(default=dict, verbose_name="Context")),
                (
                    "subject",
                    models.TextField(
                        default="", help_text="When provided, overrides template's content", verbose_name="Subject"
                    ),
                ),
                (
                    "content",
                    ox.apps.content.models.RichTextField(
                        default="", help_text="When provided, overrides template's content.", verbose_name="Message"
                    ),
                ),
                (
                    "recipients",
                    models.CharField(
                        help_text="A list of recipients, separated by a comma.",
                        max_length=512,
                        validators=[ox.apps.mails.models.validate_email_list],
                        verbose_name="Recipients",
                    ),
                ),
                (
                    "attachments",
                    models.ManyToManyField(related_name="+", to="ox_files.file", verbose_name="Attach files"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="caps.agent", verbose_name="Owner"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mail",
                "verbose_name_plural": "Mails",
            },
        ),
        migrations.CreateModel(
            name="MailAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name="Id")),
                (
                    "expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Defines an expiration date after which the access is not longer valid.",
                        null=True,
                        verbose_name="Expiration",
                    ),
                ),
                ("grants", models.JSONField(blank=True, verbose_name="Granted permissions")),
                (
                    "emitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Emitter",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived",
                        to="ox_mails.mailaccess",
                        verbose_name="Origin",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="ox_mails.mail",
                        verbose_name="Target",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "proxy": False,
            },
        ),
        migrations.CreateModel(
            name="MailAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="Id")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "mail_header",
                    ox.apps.content.models.RichTextField(
                        blank=True,
                        help_text="Emails' header at the top of all mails",
                        null=True,
                        verbose_name="Mail Header",
                    ),
                ),
                (
                    "mail_signature",
                    ox.apps.content.models.RichTextField(
                        blank=True,
                        help_text="Email signature appent to all mails' content",
                        null=True,
                        verbose_name="Signature",
                    ),
                ),
                (
                    "mail_subscription_footer",
                    ox.apps.content.models.RichTextField(
                        blank=True,
                        help_text="Footer appent below mails send to contacts of subscription contact lists.",
                        null=True,
                        verbose_name="Subscription Footer",
                    ),
                ),
                ("smtp_host", models.CharField(max_length=255, verbose_name="Host (SMTP)")),
                ("smtp_port", models.PositiveIntegerField(default=587, verbose_name="Port (SMTP)")),
                (
                    "smtp_username",
                    encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name="Username (SMTP)"),
                ),
                (
                    "smtp_password",
                    encrypted_fields.fields.EncryptedCharField(max_length=128, verbose_name="Password (SMTP)"),
                ),
                (
                    "smtp_encryption",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "NONE"), (1, "TLS"), (2, "SSL")], default=2, verbose_name="Encryption (SMTP)"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="caps.agent", verbose_name="Owner"
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Account",
                "verbose_name_plural": "Email Accounts",
            },
        ),
        migrations.AddField(
            model_name="mail",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ox_mails.mailaccount", verbose_name="Account"
            ),
        ),
        migrations.CreateModel(
            name="MailAccountAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name="Id")),
                (
                    "expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Defines an expiration date after which the access is not longer valid.",
                        null=True,
                        verbose_name="Expiration",
                    ),
                ),
                ("grants", models.JSONField(blank=True, verbose_name="Granted permissions")),
                (
                    "emitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Emitter",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived",
                        to="ox_mails.mailaccountaccess",
                        verbose_name="Origin",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="ox_mails.mailaccount",
                        verbose_name="Target",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "proxy": False,
            },
        ),
    ]
