# Generated by Django 5.2.2 on 2025-06-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_contacts", "0001_initial"),
        ("ox_mails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendmail",
            name="contact_lists",
            field=models.ManyToManyField(to="ox_contacts.contactlist", verbose_name="Contact Lists"),
        ),
        migrations.AlterField(
            model_name="sendmail",
            name="contacts",
            field=models.ManyToManyField(to="ox_contacts.contact", verbose_name="Contacts"),
        ),
    ]
