# Generated by Django 5.2.2 on 2025-06-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_mails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailaccount",
            name="imap_ssl",
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name="IMAP: Use SSL"),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="smtp_encryption",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "NONE"), (1, "TLS"), (2, "SSL")], default=2, verbose_name="SMTP: Encryption"
            ),
        ),
    ]
