# Generated by Django 5.2.2 on 2026-01-12 13:38

import encrypted_fields.fields
import ox.apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_files", "0002_alter_folder_is_sync_filecomment_foldercomment"),
        ("ox_mails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="attachments",
            field=models.ManyToManyField(related_name="+", to="ox_files.file", verbose_name="Attached files"),
        ),
        migrations.AlterField(
            model_name="mail",
            name="content",
            field=ox.apps.content.models.RichTextField(default="", verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="mail",
            name="subject",
            field=models.TextField(default="", verbose_name="Subject"),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="mail_header",
            field=ox.apps.content.models.RichTextField(
                blank=True,
                help_text="Header displayed at the top of all messages.",
                null=True,
                verbose_name="Mail Header",
            ),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="mail_signature",
            field=ox.apps.content.models.RichTextField(
                blank=True,
                help_text="The signature displayed at the end of all messages.",
                null=True,
                verbose_name="Signature",
            ),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="mail_subscription_footer",
            field=ox.apps.content.models.RichTextField(
                blank=True,
                help_text="Message displayed on mails for contacts of subscription lists.",
                null=True,
                verbose_name="Subscription Message",
            ),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="smtp_encryption",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "None"), (1, "TLS"), (2, "SSL")],
                default=2,
                verbose_name="Encryption (SMTP)",
            ),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="smtp_host",
            field=models.CharField(max_length=255, verbose_name="Host"),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="smtp_password",
            field=encrypted_fields.fields.EncryptedCharField(max_length=128, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="smtp_port",
            field=models.PositiveIntegerField(default=587, verbose_name="Port"),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="smtp_username",
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name="Username"),
        ),
    ]
