# Generated by Django 5.2.2 on 2026-01-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ox_mails", "0002_alter_mail_attachments_alter_mail_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailaccess",
            options={"verbose_name": "Mail", "verbose_name_plural": "Mails"},
        ),
        migrations.AlterModelOptions(
            name="mailaccountaccess",
            options={
                "verbose_name": "Email Account",
                "verbose_name_plural": "Email Accounts",
            },
        ),
    ]
