# Generated by Django 5.2.2 on 2025-06-19 15:59

import django.utils.timezone
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_mails", "0002_alter_mailaccount_imap_ssl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtemplate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Created"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailtemplate",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="imap_folder",
            field=models.CharField(default="INBOX", max_length=255, verbose_name="Folder (IMAP)"),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="imap_host",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Host (IMAP)"),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="imap_password",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=128, null=True, verbose_name="Password (IMAP)"
            ),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="imap_port",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Port (IMAP)"),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="imap_ssl",
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name="Use SSL (IMAP)"),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="imap_username",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=255, null=True, verbose_name="Username (IMAP)"
            ),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="smtp_encryption",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "NONE"), (1, "TLS"), (2, "SSL")], default=2, verbose_name="Encryption (SMTP)"
            ),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="smtp_host",
            field=models.CharField(max_length=255, verbose_name="Host (SMTP)"),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="smtp_password",
            field=encrypted_fields.fields.EncryptedCharField(max_length=128, verbose_name="Password (SMTP)"),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="smtp_port",
            field=models.PositiveIntegerField(default=587, verbose_name="Port (SMTP)"),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="smtp_username",
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name="Username (SMTP)"),
        ),
    ]
