# Generated by Django 5.2.2 on 2025-06-27 10:43

import ox.apps.content.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ox_mails", "0002_sendmail_contact_lists_alter_sendmail_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailaccount",
            name="mail_header",
            field=ox.apps.content.models.RichTextField(
                blank=True, help_text="Emails' header at the top of all mails", null=True, verbose_name="Mail Header"
            ),
        ),
        migrations.AddField(
            model_name="mailaccount",
            name="mail_signature",
            field=ox.apps.content.models.RichTextField(
                blank=True,
                help_text="Email signature appent to all mails' content",
                null=True,
                verbose_name="Signature",
            ),
        ),
        migrations.AddField(
            model_name="mailaccount",
            name="mail_subscription_footer",
            field=ox.apps.content.models.RichTextField(
                blank=True,
                help_text="Footer appent below mails send to contacts of subscription contact lists.",
                null=True,
                verbose_name="Subscription Footer",
            ),
        ),
    ]
