# Generated by Django 5.2.2 on 2025-06-20 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_contacts", "0003_alter_address_contact_alter_bankaccount_contact_and_more"),
        ("ox_mails", "0003_mailtemplate_created_mailtemplate_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailtemplate",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ox_mails.mailaccount",
                verbose_name="Account",
            ),
        ),
        migrations.AlterField(
            model_name="sendmail",
            name="contacts",
            field=models.ManyToManyField(to="ox_contacts.person", verbose_name="Recipients"),
        ),
    ]
