# Generated by Django 5.2.2 on 2025-06-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_mails", "0004_alter_mailtemplate_account_alter_sendmail_contacts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sendmail",
            name="status",
        ),
        migrations.AddField(
            model_name="sendmail",
            name="state",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Draft"), (1, "Sending"), (2, "Sent"), (3, "Error")], default=0, verbose_name="State"
            ),
        ),
    ]
