# Generated by Django 5.2.2 on 2025-06-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_files", "0004_alter_file_ariadescription_alter_file_caption"),
        ("ox_mails", "0005_remove_sendmail_status_sendmail_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailtemplateaccess",
            name="target",
        ),
        migrations.AlterField(
            model_name="sendmail",
            name="template",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_template": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ox_mails.sendmail",
            ),
        ),
        migrations.RemoveField(
            model_name="mailtemplateaccess",
            name="emitter",
        ),
        migrations.RemoveField(
            model_name="mailtemplateaccess",
            name="origin",
        ),
        migrations.RemoveField(
            model_name="mailtemplateaccess",
            name="receiver",
        ),
        migrations.AddField(
            model_name="sendmail",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ox_mails.mailaccount",
                verbose_name="Account",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sendmail",
            name="is_template",
            field=models.BooleanField(
                default=False, help_text="This mail is used as a template of other mails.", verbose_name="Is template"
            ),
        ),
        migrations.CreateModel(
            name="MailAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ox_files.file", verbose_name="File"
                    ),
                ),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ox_mails.sendmail", verbose_name="Mail"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="MailTemplate",
        ),
        migrations.DeleteModel(
            name="MailTemplateAccess",
        ),
    ]
