# Generated by Django 5.2.2 on 2025-06-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_files", "0004_alter_file_ariadescription_alter_file_caption"),
        ("ox_mails", "0006_remove_mailtemplateaccess_target_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendmail",
            name="attachments",
            field=models.ManyToManyField(related_name="+", to="ox_files.file", verbose_name="Attach files"),
        ),
        migrations.DeleteModel(
            name="MailAttachment",
        ),
    ]
