# Generated by Django 5.1.4 on 2025-05-08 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("code", models.CharField(db_index=True, max_length=2, verbose_name="Code")),
                ("code_3", models.CharField(db_index=True, max_length=3, verbose_name="Code 3")),
                ("phone", models.PositiveIntegerField(max_length=4, verbose_name="Phone prefix")),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
    ]
