# Generated by Django 5.2.2 on 2025-06-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name": "Currency", "verbose_name_plural": "Currencies"},
        ),
        migrations.AlterField(
            model_name="country",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ox_locations.currency",
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="is_iso",
            field=models.BooleanField(verbose_name="Is ISO"),
        ),
    ]
