# Generated by Django 5.2.1 on 2025-06-03 17:28

import django.db.models.deletion
import ox.apps.files.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("caps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="Id")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=256, null=True, verbose_name="Description"),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "file",
                    models.FileField(
                        null=True, upload_to=ox.apps.files.models.file.file_upload_to, verbose_name="File"
                    ),
                ),
                (
                    "preview",
                    models.FileField(blank=True, null=True, verbose_name="Preview"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=127, verbose_name="Mime Type")),
                ("file_size", models.PositiveIntegerField(blank=True, verbose_name="File Size")),
                (
                    "caption",
                    models.TextField(
                        default="", help_text="Displayed below object when rendered.", verbose_name="Caption"
                    ),
                ),
                (
                    "alternate",
                    models.TextField(
                        default="",
                        help_text="Displayed as replacement text when object is not displayed.",
                        verbose_name="Alternate text",
                    ),
                ),
                ("ariaDescription", models.TextField(default="", verbose_name="ARIA Description")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="caps.agent", verbose_name="Owner"
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
            },
        ),
        migrations.CreateModel(
            name="FileAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name="Id")),
                (
                    "expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Defines an expiration date after which the access is not longer valid.",
                        null=True,
                        verbose_name="Expiration",
                    ),
                ),
                ("grants", models.JSONField(blank=True, verbose_name="Granted permissions")),
                (
                    "emitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Emitter",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived",
                        to="ox_files.fileaccess",
                        verbose_name="Origin",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="ox_files.file",
                        verbose_name="Target",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "proxy": False,
            },
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="Id")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("tree_id", models.PositiveIntegerField(blank=True, verbose_name="Tree id")),
                ("level", models.PositiveIntegerField(blank=True, default=0, verbose_name="Tree level")),
                ("path", models.CharField(db_index=True, max_length=512, verbose_name="Path")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="caps.agent", verbose_name="Owner"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ox_files.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Folder",
                "verbose_name_plural": "Folders",
            },
        ),
        migrations.AddField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="ox_files.folder",
            ),
        ),
        migrations.CreateModel(
            name="FolderAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name="Id")),
                (
                    "expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Defines an expiration date after which the access is not longer valid.",
                        null=True,
                        verbose_name="Expiration",
                    ),
                ),
                ("grants", models.JSONField(blank=True, verbose_name="Granted permissions")),
                (
                    "emitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Emitter",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived",
                        to="ox_files.folderaccess",
                        verbose_name="Origin",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="ox_files.folder",
                        verbose_name="Target",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "proxy": False,
            },
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                models.F("parent"), models.F("name"), models.F("owner"), name="unique_folder_name"
            ),
        ),
    ]
