# Generated by Django 5.2.2 on 2025-06-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="alternate",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Displayed as replacement text when object is not displayed.",
                null=True,
                verbose_name="Alternate text",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="ariaDescription",
            field=models.TextField(blank=True, default="", null=True, verbose_name="ARIA Description"),
        ),
        migrations.AlterField(
            model_name="file",
            name="caption",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Displayed below object when rendered.",
                null=True,
                verbose_name="Caption",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name="File Size"),
        ),
        migrations.AlterField(
            model_name="file",
            name="preview",
            field=models.FileField(blank=True, null=True, upload_to="", verbose_name="Preview"),
        ),
    ]
