# Generated by Django 5.2.2 on 2026-01-12 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_files", "0002_alter_folder_is_sync_filecomment_foldercomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filecomment",
            name="file",
        ),
        migrations.RemoveField(
            model_name="foldercomment",
            name="folder",
        ),
        migrations.AddField(
            model_name="filecomment",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ox_files.filecomment",
                verbose_name="Related Message",
            ),
        ),
        migrations.AddField(
            model_name="foldercomment",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ox_files.foldercomment",
                verbose_name="Related Message",
            ),
        ),
        migrations.AlterField(
            model_name="filecomment",
            name="thread",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="ox_files.file",
                verbose_name="File",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="foldercomment",
            name="thread",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="ox_files.folder",
                verbose_name="Folder",
            ),
            preserve_default=False,
        ),
    ]
