# Generated by Django 5.2.2 on 2025-06-16 11:28

import ox.apps.files.models.folder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_files", "0002_alter_file_alternate_alter_file_ariadescription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="is_sync",
            field=models.BooleanField(
                default=False,
                help_text="Files and folders are synchronized to filesystem. ",
                verbose_name="Synchronize",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.CharField(
                max_length=128, validators=[ox.apps.files.models.folder.validate_name], verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="name",
            field=models.CharField(
                max_length=64, validators=[ox.apps.files.models.folder.validate_name], verbose_name="Name"
            ),
        ),
    ]
