# Generated by Django 5.2.2 on 2025-06-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_files", "0003_folder_sync_path_alter_file_name_alter_folder_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="ariaDescription",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Provide a description of the content for visually impaired people.",
                null=True,
                verbose_name="ARIA Description",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="caption",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Displayed below object when rendered in page or documents.",
                null=True,
                verbose_name="Caption",
            ),
        ),
    ]
