# Generated by Django 5.2.2 on 2026-01-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_files", "0003_remove_filecomment_file_remove_foldercomment_folder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filecomment",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Message"), (1, "Agent Message"), (16, "System"), (17, "Notification")],
                default=1,
                verbose_name="Type",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="foldercomment",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Message"), (1, "Agent Message"), (16, "System"), (17, "Notification")],
                default=1,
                verbose_name="Type",
            ),
            preserve_default=False,
        ),
    ]
