# Generated by Django 5.2.2 on 2026-01-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_files", "0004_filecomment_type_foldercomment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="description",
            field=models.CharField(blank=True, default="", max_length=256, null=True, verbose_name="Description"),
        ),
    ]
