# Generated by Django 5.2.2 on 2026-01-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_files", "0005_folder_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filecomment",
            name="type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Message"),
                    (1, "Agent Message"),
                    (16, "System"),
                    (17, "Notification"),
                ],
                default=0,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="foldercomment",
            name="type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Message"),
                    (1, "Agent Message"),
                    (16, "System"),
                    (17, "Notification"),
                ],
                default=0,
                verbose_name="Type",
            ),
        ),
    ]
