# Generated by Django 5.2.2 on 2026-01-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_files", "0006_alter_filecomment_type_alter_foldercomment_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fileaccess",
            options={"verbose_name": "File", "verbose_name_plural": "Files"},
        ),
        migrations.AlterModelOptions(
            name="folderaccess",
            options={"verbose_name": "Folder", "verbose_name_plural": "Folders"},
        ),
        migrations.RemoveField(
            model_name="folder",
            name="is_sync",
        ),
        migrations.AlterField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="ox_files.folder",
                verbose_name="Folder",
            ),
        ),
    ]
