# Generated by Django 5.2.2 on 2026-01-26 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_files", "0007_alter_fileaccess_options_alter_folderaccess_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="ox_files.folder",
                verbose_name="Folder",
            ),
            preserve_default=False,
        ),
    ]
