export { default as OxMailAccountEdit} from './OxMailAccountEdit.vue'
export { default as OxMailAccountPanel} from './OxMailAccountPanel.vue'
export { default as OxMailTemplateEdit} from './OxMailTemplateEdit.vue'
export { default as OxMailTemplatePanel} from './OxMailTemplatePanel.vue'
export { default as OxOutMailEdit} from './OxOutMailEdit.vue'
export { default as OxOutMailPanel} from './OxOutMailPanel.vue'
