export { default as OxMailAccountEdit} from './OxMailAccountEdit.vue'
export { default as OxMailAccountPanel} from './OxMailAccountPanel.vue'
export { default as OxMailTemplateEdit} from './OxMailTemplateEdit.vue'
export { default as OxMailTemplatePanel} from './OxMailTemplatePanel.vue'
export { default as OxSendMailEdit} from './OxSendMailEdit.vue'
export { default as OxSendMailPanel} from './OxSendMailPanel.vue'
