# Generated by Django 5.1.4 on 2025-05-06 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Object reference",
                        verbose_name="Id",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Object reference",
                        verbose_name="Id",
                    ),
                ),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                        verbose_name="Kind",
                    ),
                ),
                ("street", models.CharField(max_length=128, verbose_name="Street")),
                ("street_2", models.CharField(max_length=128, verbose_name="Street 2")),
                ("number", models.IntegerField(verbose_name="Number")),
                ("box", models.IntegerField(blank=True, null=True, verbose_name="Box")),
                ("postcode", models.IntegerField(verbose_name="Postcode")),
                ("city", models.CharField(max_length=128, verbose_name="City")),
                ("country", models.CharField(max_length=32, verbose_name="Country")),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact")),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Object reference",
                        verbose_name="Id",
                    ),
                ),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                        verbose_name="Kind",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact")),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Object reference",
                        verbose_name="Id",
                    ),
                ),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                        verbose_name="Kind",
                    ),
                ),
                ("number", models.CharField(max_length=32, verbose_name="Phone")),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact")),
            ],
            options={
                "verbose_name": "Phone",
                "verbose_name_plural": "Phones",
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "contact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ox_contacts.contact",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("description", models.CharField(max_length=256, verbose_name="Description")),
                ("company_form", models.CharField(max_length=64, verbose_name="Company Form")),
                ("number", models.CharField(blank=True, default="", max_length=32, verbose_name="Number")),
                ("vat", models.CharField(blank=True, default="", max_length=32, verbose_name="VAT")),
                ("country", models.CharField(max_length=32, verbose_name="Country")),
                (
                    "group",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="auth.group"
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
            },
            bases=("ox_contacts.contact", models.Model),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "contact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ox_contacts.contact",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=64, verbose_name="First name")),
                ("last_name", models.CharField(default="", max_length=64, verbose_name="Last name")),
                ("organisations", models.ManyToManyField(blank=True, null=True, to="ox_contacts.organisation")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
            },
            bases=("ox_contacts.contact",),
        ),
    ]
