# Generated by Django 5.1.4 on 2025-05-27 14:09

import django.db.models.deletion
import ox.utils.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ox_locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                        default=0,
                        verbose_name="Kind",
                    ),
                ),
                ("iban", models.CharField(max_length=40, verbose_name="IBAN")),
                ("bic", models.CharField(max_length=11, verbose_name="SWIFT/BIC")),
                ("address", models.CharField(max_length=128, verbose_name="Address")),
                ("bank_name", models.CharField(max_length=128, verbose_name="Bank Name")),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact")),
            ],
            options={
                "verbose_name": "IBAN Account",
                "verbose_name_plural": "IBAN Accounts",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                        default=0,
                        verbose_name="Kind",
                    ),
                ),
                ("street", models.CharField(max_length=128, verbose_name="Street")),
                ("street_2", models.CharField(blank=True, default="", max_length=128, verbose_name="Street 2")),
                ("number", models.CharField(max_length=16, verbose_name="Number")),
                ("box", models.CharField(blank=True, default="", max_length=16, verbose_name="Box")),
                ("postcode", models.PositiveIntegerField(verbose_name="Postcode")),
                ("city", models.CharField(max_length=128, verbose_name="City")),
                (
                    "country",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="ox_locations.country"
                    ),
                ),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact")),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                        default=0,
                        verbose_name="Kind",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact")),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
                "default_related_name": "email_set",
            },
        ),
        migrations.CreateModel(
            name="OrganisationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("code", models.CharField(blank=True, default="", max_length=8, verbose_name="Code")),
                ("abbreviation", models.CharField(blank=True, default="", max_length=32, verbose_name="Abbreviation")),
                ("language_code", models.CharField(blank=True, default="", max_length=4, verbose_name="Language Code")),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ox_locations.country")),
            ],
            options={
                "verbose_name": "Company Form",
                "verbose_name_plural": "Company Forms",
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                        default=0,
                        verbose_name="Kind",
                    ),
                ),
                ("number", models.CharField(max_length=32, verbose_name="Phone")),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact")),
            ],
            options={
                "verbose_name": "Phone",
                "verbose_name_plural": "Phones",
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "contact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ox_contacts.contact",
                    ),
                ),
                ("color", ox.utils.models.ColorField(blank=True, max_length=7, null=True, verbose_name="Color")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=256, null=True, verbose_name="Description"),
                ),
                ("short_name", models.CharField(blank=True, max_length=32, null=True, verbose_name="Short name")),
                ("reference", models.CharField(blank=True, default="", max_length=32, verbose_name="Reference Number")),
                ("vat", models.CharField(blank=True, max_length=32, null=True, verbose_name="VAT")),
                (
                    "country",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ox_locations.country"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ox_contacts.organisationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
            },
            bases=("ox_contacts.contact", models.Model),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "contact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ox_contacts.contact",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=64, verbose_name="First name")),
                ("last_name", models.CharField(default="", max_length=64, verbose_name="Last name")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="Email")),
                ("organisations", models.ManyToManyField(blank=True, null=True, to="ox_contacts.organisation")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
            },
            bases=("ox_contacts.contact",),
        ),
    ]
