# Generated by Django 5.1.4 on 2025-05-06 14:09

import django.db.models.deletion
import ox.utils.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ox_contacts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="color",
            field=ox.utils.models.ColorField(blank=True, max_length=7, null=True, verbose_name="Color"),
        ),
        migrations.AlterField(
            model_name="address",
            name="box",
            field=models.CharField(blank=True, default="", max_length=16, verbose_name="Box"),
        ),
        migrations.AlterField(
            model_name="address",
            name="kind",
            field=models.SmallIntegerField(
                choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                default=0,
                verbose_name="Kind",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postcode",
            field=models.PositiveIntegerField(verbose_name="Postcode"),
        ),
        migrations.AlterField(
            model_name="address",
            name="street_2",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="Street 2"),
        ),
        migrations.AlterField(
            model_name="address",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference"),
        ),
        migrations.AlterField(
            model_name="email",
            name="kind",
            field=models.SmallIntegerField(
                choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                default=0,
                verbose_name="Kind",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference"),
        ),
        migrations.AlterField(
            model_name="person",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="kind",
            field=models.SmallIntegerField(
                choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                default=0,
                verbose_name="Kind",
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference"),
        ),
    ]
