# Generated by Django 5.2.2 on 2025-06-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="organisations",
            field=models.ManyToManyField(blank=True, to="ox_contacts.organisation"),
        ),
    ]
