# Generated by Django 5.1.4 on 2025-05-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ox_contacts", "0002_organisation_color_alter_address_box_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("code", models.CharField(db_index=True, max_length=2, verbose_name="Code")),
                ("code_3", models.CharField(db_index=True, max_length=3, verbose_name="Code 3")),
                ("phone", models.PositiveIntegerField(max_length=4, verbose_name="Phone prefix")),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="number",
            field=models.CharField(max_length=16, verbose_name="Number"),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="description",
            field=models.CharField(blank=True, default="", max_length=256, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.country"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="country",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.country"
            ),
        ),
    ]
