# Generated by Django 5.2.2 on 2025-06-19 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_contacts", "0002_alter_person_organisations"),
        ("ox_locations", "0002_alter_currency_options_alter_country_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact", verbose_name="Contact"
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact", verbose_name="Contact"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact", verbose_name="Contact"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ox_locations.country",
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="short_name",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="Short Name"),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ox_contacts.organisationtype",
                verbose_name="Organisation Type",
            ),
        ),
        migrations.AlterField(
            model_name="organisationtype",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ox_locations.country", verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="organisations",
            field=models.ManyToManyField(blank=True, to="ox_contacts.organisation", verbose_name="Organisations"),
        ),
        migrations.AlterField(
            model_name="person",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="This contact is related to a user of the plateform",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact", verbose_name="Contact"
            ),
        ),
    ]
