# Generated by Django 5.2.2 on 2025-06-24 13:41

import ox.utils.models.color
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_contacts", "0003_alter_address_contact_alter_bankaccount_contact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("color", ox.utils.models.color.ColorField(blank=True, max_length=7, null=True, verbose_name="Color")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=256, null=True, verbose_name="Description"),
                ),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                (
                    "is_subscription",
                    models.BooleanField(
                        help_text="This list is used for mailing-lists. This allows contacts to unsubscribe from the list among other things.",
                        verbose_name="Subscription list",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact List",
                "verbose_name_plural": "Contact Lists",
            },
        ),
        migrations.AddField(
            model_name="person",
            name="contact_lists",
            field=models.ManyToManyField(blank=True, to="ox_contacts.contactlist", verbose_name="Lists"),
        ),
    ]
