# Generated by Django 5.1.4 on 2025-05-08 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ox_contacts", "0003_country_alter_address_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="country",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ox_contacts.country"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="vat",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="VAT"),
        ),
        migrations.CreateModel(
            name="OrganisationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.country")),
            ],
            options={
                "verbose_name": "Company Form",
                "verbose_name_plural": "Company Forms",
            },
        ),
        migrations.AlterField(
            model_name="organisation",
            name="company_form",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ox_contacts.organisationtype"
            ),
        ),
    ]
