# Generated by Django 5.2.2 on 2025-06-25 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("ox_contacts", "0004_contactlist_person_contact_lists"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactlist",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="This list is related to a user group",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
                verbose_name="Group",
            ),
        ),
        migrations.AddField(
            model_name="contactlist",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                help_text="This list is related to an organisation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ox_contacts.organisation",
                verbose_name="Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="contactlist",
            name="is_subscription",
            field=models.BooleanField(
                help_text="This list is used for mailing-lists. It allows contacts to unsubscribe from the list among other things.",
                verbose_name="Subscription list",
            ),
        ),
    ]
