# Generated by Django 5.1.4 on 2025-05-08 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ox_contacts", "0004_alter_organisation_country_alter_organisation_vat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organisation",
            old_name="company_form",
            new_name="type",
        ),
    ]
