# Generated by Django 5.2.2 on 2025-06-25 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("ox_contacts", "0005_contactlist_group_contactlist_organisation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactlist",
            name="group",
            field=models.OneToOneField(
                blank=True,
                help_text="This list is related to a group",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_list",
                to="auth.group",
                verbose_name="Group",
            ),
        ),
        migrations.AlterField(
            model_name="contactlist",
            name="organisation",
            field=models.OneToOneField(
                blank=True,
                help_text="This list is related to an organisation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_list",
                to="ox_contacts.organisation",
                verbose_name="Organisation",
            ),
        ),
    ]
