# Generated by Django 5.1.4 on 2025-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ox_contacts", "0005_rename_company_form_organisation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationtype",
            name="code",
            field=models.CharField(blank=True, default="", max_length=8, verbose_name="Abbreviation"),
        ),
    ]
