# Generated by Django 5.2.2 on 2025-06-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_contacts", "0006_alter_contactlist_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactlist",
            name="is_subscription",
            field=models.BooleanField(
                default=False,
                help_text="This list is used for mailing-lists. It allows contacts to unsubscribe from the list among other things.",
                verbose_name="Subscription list",
            ),
        ),
    ]
