# Generated by Django 5.1.4 on 2025-05-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ox_contacts", "0006_organisationtype_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="description",
            field=models.CharField(blank=True, default="", max_length=256, null=True, verbose_name="Description"),
        ),
    ]
