# Generated by Django 5.1.4 on 2025-05-08 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ox_contacts", "0007_alter_organisation_description"),
        ("ox_locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="country",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ox_locations.country"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="ox_locations.country"
            ),
        ),
        migrations.AlterField(
            model_name="organisationtype",
            name="country",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ox_locations.country"),
        ),
        migrations.AddField(
            model_name="organisationtype",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference"),
        ),
        migrations.DeleteModel(
            name="Country",
        ),
    ]
