# Generated by Django 5.2.2 on 2025-06-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_contacts", "0007_alter_contactlist_is_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="contact_lists",
        ),
        migrations.RemoveField(
            model_name="person",
            name="email",
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_lists",
            field=models.ManyToManyField(
                blank=True, related_name="contacts", to="ox_contacts.contactlist", verbose_name="Lists"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="person",
            name="organisations",
            field=models.ManyToManyField(
                blank=True, related_name="persons", to="ox_contacts.organisation", verbose_name="Organisations"
            ),
        ),
    ]
